files =  main.cpp dungeon.cpp ../libtile/libtile.a
flags = -std=c++20
libs = -lraylib  -L /opt/homebrew/lib  
includes = -I ../libstrings -I ../libtile/ 
make: $(files)
	g++  $(files) $(includes) $(flags) $(libs)
