[package]
name = "cities"
version = "0.1.0"
edition = "2024"

[dependencies]
bindgen = "0.71.1"
pprof = { version = "0.14", features = ["flamegraph"] }
rand = "0.9.0"
raylib-rs = "0.1.0"

[profile.release]
debug = false
