make: main.cpp Abilities.cpp Ancestries.cpp Character.cpp Spellcasting.cpp Utils.cpp personality.cpp
	g++ main.cpp Abilities.cpp Ancestries.cpp Character.cpp Spellcasting.cpp Utils.cpp personality.cpp grimoire.cpp -g3 -std=c++20 -fsanitize=address
windows:main.cpp Abilities.cpp Ancestries.cpp Character.cpp Spellcasting.cpp Utils.cpp 
	i686-w64-mingw32-c++ main.cpp Abilities.cpp Ancestries.cpp Character.cpp Spellcasting.cpp Utils.cpp -o CharacterGen -g3 -std=c++20
