//  Names.h
//  Pathfinder_Character_Generator
//
//  Created by Isaac Hartin Pasco on 7/7/23.
//

#ifndef Names_h
#define Names_h
#include <string>
#include <vector>
using namespace std;
inline vector<string> HumanMascFirstNames = {"Alan", "Alun", "Arthur", "Arthyen", "Austell", "Benesek", "Blyth", "Branek", "Branwalather", "Brengy",
"Breoc", "Bryok", "Budic", "Buthek", "Cadan", "Cador", "Cadreth", "Caradoc", "Carasek", "Carrow", "Caswyn", "Cleder", "Clemow", "Clesek",
"Colan", "Colyn", "Corentyn", "Cornelly", "Costentyn", "Costetyn", "Crantok", "Credan", "Daveth", "Davy", "Denzel", "Digory", "Docco", "Doniert",
"Donyerth", "Durngarth", "Elid", "Enoder", "Ervan", "Feoc", "Gawen", "Gerens", "Gerent", "Germoc", "Germoe", "Glewas", "Goran", "Gorlas", "Goron",
"Gorthelyk", "Gourgy", "Gwinear", "Gwynek", "Herygh", "Hicca", "Howel", "Hydroc", "Iahan", "Ives", "Jacca", "Jago", "Jamma", "Jory", "Jowan", "Kaveran",
"Kenal", "Kenan", "Kenver", "Kenwyn", "Keresyk", "Kevern", "Kitto", "Ludwan", "Maban", "Madern", "Malgen", "Manuel", "Margh", "Marrek", "Massen", "Mawgan",
"Maylwen", "Mellyan", "Melor", "Melyn", "Meriasek", "Merryn", "Milyan", "Myghal", "Nadelek", "Nechtan", "Nerth", "Neythen", "Nicca", "Padern", "Pasco", "Pawly",
"Peder", "Pencast", "Peran", "Perran", "Petroc", "Petrok", "Piran", "Rewan", "Ruan", "Rumon", "Ryel", "Samson", "Seleven", "Selyf", "Sennen", "Silyen", "Sithny",
"Sythyn", "Talan", "Talek", "Tomas", "Trevedic", "Tristan", "Trystan", "Udy", "Uther", "Uthno", "Vark", "Vyvyan", "Welet", "Wella", "Weryn", "Wethinoc", "Withell",
"Worrec", "Yestin", "Ythel"};

inline vector<string> HumanFemmeFirstNames =  {"Ailla", "Angelet", "Arranz", "Athwenna", "Banallan", "Barenwyn", "Berlewen", "Bersaba", "Beryan", "Blejan",
"Bryluen", "Burien", "Caja", "Carenza", "Ceinwen", "Chesten", "Columba", "Conwenna", "Cordelia", "Crewenna", "Cryda", "Delen", "Demelza", "Derowen",
"Derwa", "Dywana", "Ebrel", "Elestren", "Elowen", "Endelienta", "Endelyon", "Eseld", "Eselt", "Esyld", "Eva", "Ewa", "Ewe", "Glanna", "Gweniver", "Gwennol",
"Hedra", "Jenifer", "Jenifry", "Jenna", "Jowanet", "Kayna", "Kelynen", "Kensa", "Kerensa", "Kerenza", "Keresyk", "Kerra", "Kew", "Ladoca", "Loveday", "Lowenek",
 "Lowenna", "Mabyn", "Manacca", "Mariot", "Marya", "Melior", "Meliora", "Mellear", "Melloney", "Mellyn", "Melwyn", "Melyar", "Melyonen", "Melyor", "Meraud", "Merouda",
"Metheven", "Morenwyn", "Morgelyn", "Morveren", "Morvoren", "Morwen", "Morwenna", "Morwennol", "Morwetha", "Neraud", "Nessa", "Newlyn", "Newlyna", "Nonna", "Rosen",
"Rozen", "Rozenwyn", "Senara", "Sevi", "Sowena", "Steren", "Talwyn", "Tamara", "Tamsyn", "Tecca", "Tegen", "Tregereth", "Tressa", "Trevenna", "Tryfena", "Vorva",
"Weneppa", "Wenn", "Wenna", "Wylmet", "Ygerna", "Zethar"};

inline vector<string>  humanLastNames = {"Andrewartha", "Angrave", "Annear", "Anning", "Bain", "Baragwanath", "Beckerleg", "Bedell", "Bennetto", "Bennetts", "Berriman",
"Berryman", "Bescoby", "Bice", "Biddick", "Binney", "Blamey", "Boase", "Boden", "Bolitho", "Bonython", "Borlase", "Bosanko", "Bosanquet", "Bray", "Briddon", "Bryant",
"Carbines", "Cardell", "Care", "Carlyon", "Carnell", "Carveth", "Causley", "Chegwidden", "Chenhalls", "Chenoweth", "Clemow", "Clemson", "Climo", "Clymo", "Coad", "Cocking",
"Colenso", "Colley", "Congdon", "Corin", "Couch", "Cowling", "Craddick", "Crago", "Craze", "Crowle", "Cundy", "Curnow", "Daniel", "Deveril", "Dobell", "Dowling", "Eade",
"Edwards", "Ellis", "Endean", "Eva", "Faull", "Frayne", "Freeman", "Freethy", "Galtey", "Geach", "Geake", "Godden", "Gole", "Goss", "Gribbin", "Gynn", "Hain", "Haines",
"Hambly", "Hannaford", "Hannah", "Harris", "Hayne", "Hendra", "Hobby", "Hocking", "Hodge", "Hollow", "Hosking", "Hoskins", "Inch", "Isbell", "Ivey", "James", "Jasper",
"Jelbart", "Jennings", "Jewell", "Johns", "Joliffe", "Jolly", "Keast", "Keen", "Keigwin", "Kempthorne", "Kersey", "Kestle", "Kinver", "Kittow", "Lander", "Landreth",
"Lanyon", "Lawry", "Lean", "Leggo", "Liddicoat", "Lowry", "Maddaford", "Maddern", "Magor", "Martin", "Mayne", "Menadue", "Mitchell", "Moon", "Morcom", "Murrish",
"Nancarrow", "Nankervis", "Nankivel", "Newth", "Nicholls", "Ninnis", "Noall", "Noon", "Oates", "Odgers", "Old", "Olver", "Opie", "Otes", "Palk", "Pascoe", "Pawley",
"Paynter", "Pearce", "Pellew", "Penberthy", "Pender", "Pengelly", "Penhaligon", "Penhallow", "Penn", "Penrose", "Pentreath", "Penwarden", "Perkin", "Perrin", "Peters",
"Pethick", "Phillips", "Poldark", "Polmear", "Praed", "Prowse", "Quick", "Quintrell", "Raddall", "Restorick", "Retallack", "Richards", "Rodda", "Rogers", "Rose",
"Roseveare", "Rosewall", "Rosewarne", "Roskelly", "Roskilly", "Rouncefield", "Rowe", "Rowse", "Rule", "Rundle", "Ryall", "Sanders", "Scobel", "Skewes", "Smith", "Snell",
 "Spargo", "Stevens", "Tamblyn", "Tangye", "Tanner", "Teague", "Terrill", "Thomas", "Tinney", "Tonkin", "Trebilcock", "Tredinnick", "Trefusis", "Tregear", "Tregellas",
 "Tregelles", "Tregenza", "Tregloan", "Treglown", "Tregoning", "Tregonning", "Trelawney", "Treleavin", "Treloar", "Tremain", "Tremayne", "Trembath", "Tremelling",
 "Trenance", "Trerice", "Treseder", "Tresillian", "Trestrail", "Trethew", "Trethewey", "Trethowan", "Trevain", "Trevaskis", "Trevellick", "Trevelyan", "Treverton",
 "Trevethan", "Trevithick", "Trevorrow", "Trewarthen", "Treweeke", "Trewhella", "Trewin", "Trezona", "Trounson", "Trudgen", "Truscott", "Tyack", "Uren", "Veal", "Vear",
 "Vellenoweth", "Venton", "Verran", "Vial", "Vosper", "Voss", "Warne", "Warren", "Wearne", "White", "Wickett", "Williams", "Windle", "Withiel", "Yelland", "Yourand"};

inline vector<string>  DwarfFemmeFirstNames = {"Ase", "Ægileif", "Adís", "Ágærthr", "Aldís", "Álfdís", "Álfeithr", "Álfgerthr", "Álfhildr", "Alfny", "Alfrun", "Alví",
"Alfvör", "Algun", "Álöf", "Alvoer", "Anddísi", "Arnbjórg", "Arndís", "Arneidr", "Arneithr", "Arnfríthr", "Arngerthr", "Arngunnr", "Arnkatla", "Arnlaug", "Arnleif",
"Arnljot", "Arnóra", "Arnrithr", "Arnthruthr", "Æsa", "Ásbjórg", "Ásdís", "Ásgerthr", "Ásgunnr", "Áshildr", "Áskatla", "Aslaug", "Ásleif", "Ásmóthr", "Ásny", "Ásta",
"Ástríthr", "Ásvör", "Authbjorg", "Authfríthr", "Authhildr", "Authr", "Bera", "Bergdís", "Bergljót", "Bergthóra", "Birna", "Bjargey", "Bjarlaug", "Bjollok", "Björg", "Bolla", "Bót", "Bóthæithr", "Bothildr", "Böthney", "Bótví", "Bryndís", "Bryngerthr", "Brynhildr", "Dagfrithr", "Dagny", "Dagrún", "Dalla", "Dís", "Dísælfr", "Drifa",
"Dyrdís", "Dyrfinna", "Dyrhildr", "Eirny", "Elfrithr", "Elína", "Ethna", "Eydís", "Eyja", "Eylaug", "Eyvör", "Fastgærthr", "Fasthæithr", "Fastlaug", "Fastny", "Finna",
"Fjördís", "Fjórleif", "Fregerthr", "Freydís", "Freyleif", "Frítha", "Frithgerthr", "Geirbjórg", "Geirhildr", "Geirlaug", "Geirny", "Geirríthr", "Gerthr", "Gjaflaug",
"Grélöth", "Gríma", "Gróa", "Gunnhildr", "Gunnlaug", "Gunnvör", "Guthbjörg", "Guthlaug", "Guthleif", "Guthny", "Guthríthr", "Guthrún", "Hafthóra", "Halla", "Hallbera",
 "Hallbjörg", "Halldís", "Halldóra", "Hallfríthr", "Hallgerthr", "Hallkatla", "Hallthora", "Hallveig", "Hallvör", "Heimdís", "Heimlaug", "Heithr", "Helga", "Herbjörg",
 "Herdís", "Hergerthr", "Herlaug", "Herríthr", "Herthrúthr", "Hervör", "Hildigerthr", "Hildigunnr", "Hildísif", "Hjalmdís", "Hjálmgerthr", "Hjálp", "Hjördís", "Hlíf",
 "Holmdís", "Holmfrithr", "Holmgerthr", "Holmlaug", "Hrafnhildr", "Hrefna", "Hróthny", "Húngerthr", "Ingibjörg", "Ingigerthr", "Ingileif", "Ingirun", "Ingithora",
 "Ingríthr", "Ingunn", "Ingvöldr", "Ísgerthr", "Islaug", "Isrithr", "Ithunn", "Járngerthr", "Jódís", "Jófríthr", "Jóra", "Jóreithr", "Jórunn", "Katla", "Ketilbjörg",
 "Ketilfrithr", "Ketilríthr", "Kjölvör", "Kolfinna", "Kolgríma", "Magnhildr", "Melkorka", "Mjöll", "Móeithr", "Myrgjol", "Myrún", "Nithbjörg", "Oddbjörg", "Oddfríthr",
 "Oddlaug", "Oddleif", "Oddny", "Oddrunn", "Öndótt", "Ormgerthr", "Ormhildr", "Ósk", "Otkatla", "Raförta", "Ragnfrithr", "Ragnheithr", "Ragnhildr", "Rannlaug", "Rannveig",
 "Reginhlif", "Reginleif", "Reginthruthr", "Rjúpa", "Runfrithr", "Runhildr", "Sæhildr", "Salbjörg", "Salgerthr", "Sæuthr", "Signy", "Sigríthr", "Sigrunn", "Sigthruthr",
 "Sinn", "Snælaug", "Sólveig", "Sölvör", "Steinfrithr", "Steingerthr", "Steinhildr", "Steinunn", "Steinvör", "Svana", "Svanhildr", "Svanlaug", "Thjóthgerthr", "Thjóthhildr",
 "Thóra", "Thórarna", "Thorbjörg", "Thórdís", "Thórelfr", "Thórey", "Thorfinna", "Thorgerthr", "Thorgríma", "Thórhildr", "Thorkatla", "Thorlaug", "Thorleif", "Thorlót",
 "Thórny", "Thórodda", "Thórunn", "Thórvé", "Thórvör", "Thraslaug", "Thuríthr", "Tófa", "Úlfeithr", "Úlfhildr", "Úlfrún", "Valbjörg", "Valdís", "Valgerthr", "Védís",
 "Vefreyja", "Vefrithr", "Vélaug", "Vény", "Vigdís", "Vilborg", "Vilgerthr", "Yngvildr", "  Thorgils", "Thorgrímr", "Thórhaddr", "Thórhallr", "Thórir", "Thorkell",
 "Thorlákr", "Thorleifr", "Thorleikr", "Thormóthr", "Thóroddr", "Thórólfr", "Thórormr", "Thorsteinn", "Thórthr", "Thorvaldr", "Thorvalthr", "Thorvithr", "Thóthrekr",
  "Thrainn", "Thrasi", "Thróndr", "Thröstr", "Tindr", "Tjórvi", "Torfi", "Torrathr Yngvarr", "Tyrfingr", "Úlfar", "Úlfhethinn",
  "Úlfljótr", "Úlfr", "Valbrandr", "Valgarthr", "Váli", "Vébrandr", "Végestr", "Vémundr", "Vestarr", "Vestmathr", "Véthormr", "Vífill", "Vigfúss"};

inline vector<string>  DwarfMascFirstNames= {"Álfr", "Án", "Ari", "Arinbjörn", "Ármóthr", "Arnbjórn", "Arngeirr",
  "Arngrímr", "Arnljotr", "Arnmóthr", "Arnórr", "Arnríthr", "Ásbjórn", "Ásbrandr", "Ásgeirr", "Áskell", "Áslákr",
  "Ásmólfr", "Ásmundr", "Athalsteinn", "Athils", "Atli", "Authun", "Ævarr", "Barthi", "Bárthr", "Bergr", "Bergthórr",
  "Bersi", "Bjarni", "Bjórn", "Bödmóthr", "Bogi", "Bolli", "Bölverkr", "Börkr", "Bóthvarr", "Bótólfr", "Brandr", "Brúni",
  "Brynjólfr", "Dufthakr", "Egill", "Eilífr", "Einarr", "Eindrithi", "Eiríkr", "Eldgrimr", "Eyjólfr", "Eymundr", "Eysteinn",
  "Eyvindr", "Finnbogi", "Finni", "Finnr", "Finnvarthr", "Flóki", "Flosi", "Galti", "Gautr", "Geiri", "Geirmundr", "Geirr", "Geirrøthr",
  "Geitir", "Gellir", "Gestr", "Gils", "Gísli", "Gizurr", "Glædir", "Glúmr", "Gnúpr", "Gormr", "Grani", "Grenjathr", "Grímkell", "Grímólfr", "Grímr",
   "Gríss", "Gunnarr", "Gunnjörn", "Gunnlaugr", "Gunnólfr", "Gunnsteinn", "Guthlaugr", "Guthleifr", "Guthmundr", "Guthrøthr", "Gyrthr", "Hafgrímr", "Haflithi",
   "Hafr", "Hafthórr", "Hákon", "Hálfdan", "Hallbjórn", "Halldórr", "Hallgrímr", "Halli", "Hallkell", "Hallormr", "Hallr", "Hallsteinn", "Hallvarthr", "Hámundr",
   "Haraldr", "Hárekr", "Haukr", "Hávarthr", "Helgi", "Herjólfr", "Hermundr", "Hethinn", "Hildir", "Hjalti", "Hjörleifr", "Hjörr", "Hjörtr", "Hlöthver", "Högni",
   "Hólmsteinn", "Hórthr", "Hóskuldr", "Hrafn", "Hrafnkell", "Hrani", "Hrappr", "Hrathi", "Hrærekr", "Hreitharr", "Hróaldr", "Hróarr", "Hrólfr", "Hrómundr",
   "Hróthgeirr", "Hrothmarr", "Hvati", "Illugi", "Ingjaldr", "Ingólfr", "Ísleifr", "Ísrauthr", "Ivarr", "Jökull", "Jón", "Jörundr", "Jósteinn", "Kálfr", "Kári",
   "Karl", "Karli", "Kárr", "Ketill", "Kjallakr", "Kjartan", "Klængr", "Kleppjárn", "Knjúkr", "Knörr", "Kolbeinn", "Kolgrímr", "Kolli", "Kollr", "Kollsveinn",
   "Kolr", "Kothrán", "Leithólfr", "Máni", "Már", "Mörór", "Njáll", "Oddbjörn", "Oddi", "Oddleifr", "Oddr", "Ófeigr", "Óláfr", "Óleifr", "Ölmóthr", "Ölvir", "Önundr",
   "Ørlygr", "Ormr", "Örn", "Örnólfr", "Otkell", "Óttarr", "Özurr", "Ragnarr", "Rauthulfr", "Reginulfr", "Refr", "Rúnólfr", "Sæbjörn", "Sæmundr", "Sigfastr", "Sigfúss",
   "Sighvatr", "Sigmundr", "Sigurthr", "Skagi", "Skeggi", "Skíthi", "Skjaldbjörn", "Skjálgr", "Skjóldúlfr", "Skorageirr", "Skorri", "Skúli", "Skúmr", "Snæbjörn", "Snorri",
    "Sölvi", "Starkathr", "Steinarr", "Steinbjörn", "Steingrímr", "Steinmóthr", "Steinn", "Steinólfr", "Steinrøthr", "Steinthórr", "Sturla", "Styrbjörn", "Styrmir",
    "Sumarlithi", "Surtr", "Svanr", "Svarthöfthi", "Svartr", "Sveinbjörn", "Sveinungr", "Svertingr", "Tanni", "Teitr", "Thengill", "Thithrandi", "Thjóthólfr", "Thórarinn",
    "Thorbergr", "Thorbjörn", "Thorbrandr", "Thorfinnr", "Thorgeirr", "Thorgestr"};

inline vector<string>  DwarfLastNames = {"Aase", "Ægileif", "Adís", "Ágærthr", "Aldís", "Álfdís", "Álfeithr", "Álfgerthr", "Álfhildr", "Alfny", "Alfrun", "Alví", "Alfvör",
    "Algun", "Álöf", "Alvoer", "Anddísi", "Arnbjórg", "Arndís", "Arneidr", "Arneithr", "Arnfríthr", "Arngerthr", "Arngunnr", "Arnkatla", "Arnlaug", "Arnleif", "Arnljot",
    "Arnóra", "Arnrithr", "Arnthruthr", "Æsa", "Ásbjórg", "Ásdís", "Ásgerthr", "Ásgunnr", "Áshildr", "Áskatla", "Aslaug", "Ásleif", "Ásmóthr", "Ásny", "Ásta", "Ástríthr",
    "Ásvör", "Authbjorg", "Authfríthr", "Authhildr", "Authr", "Bera", "Bergdís", "Bergljót", "Bergthóra", "Birna", "Bjargey", "Bjarlaug", "Bjollok", "Björg", "Bolla", "Bót",
     "Bóthæithr", "Bothildr", "Böthney", "Bótví", "Bryndís", "Bryngerthr", "Brynhildr", "Dagfrithr", "Dagny", "Dagrún", "Dalla", "Dís", "Dísælfr", "Drifa", "Dyrdís",
     "Dyrfinna", "Dyrhildr", "Eirny", "Elfrithr", "Elína", "Ethna", "Eydís", "Eyja", "Eylaug", "Eyvör", "Fastgærthr", "Fasthæithr", "Fastlaug", "Fastny", "Finna", "Fjördís",
      "Fjórleif", "Fregerthr", "Freydís", "Freyleif", "Frítha", "Frithgerthr", "Geirbjórg", "Geirhildr", "Geirlaug", "Geirny", "Geirríthr", "Gerthr", "Gjaflaug", "Grélöth",
      "Gríma", "Gróa", "Gunnhildr", "Gunnlaug", "Gunnvör", "Guthbjörg", "Guthlaug", "Guthleif", "Guthny", "Guthríthr", "Guthrún", "Hafthóra", "Halla", "Hallbera",
      "Hallbjörg", "Halldís", "Halldóra", "Hallfríthr", "Hallgerthr", "Hallkatla", "Hallthora", "Hallveig", "Hallvör", "Heimdís", "Heimlaug", "Heithr", "Helga", "Herbjörg",
      "Herdís", "Hergerthr", "Herlaug", "Herríthr", "Herthrúthr", "Hervör", "Hildigerthr", "Hildigunnr", "Hildísif", "Hjalmdís", "Hjálmgerthr", "Hjálp", "Hjördís", "Hlíf",
      "Holmdís", "Holmfrithr", "Holmgerthr", "Holmlaug", "Hrafnhildr", "Hrefna", "Hróthny", "Húngerthr", "Ingibjörg", "Ingigerthr", "Ingileif", "Ingirun", "Ingithora",
      "Ingríthr", "Ingunn", "Ingvöldr", "Ísgerthr", "Islaug", "Isrithr", "Ithunn", "Járngerthr", "Jódís", "Jófríthr", "Jóra", "Jóreithr", "Jórunn", "Katla", "Ketilbjörg",
      "Ketilfrithr", "Ketilríthr", "Kjölvör", "Kolfinna", "Kolgríma", "Magnhildr", "Melkorka", "Mjöll", "Móeithr", "Myrgjol", "Myrún", "Nithbjörg", "Oddbjörg", "Oddfríthr",
      "Oddlaug", "Oddleif", "Oddny", "Oddrunn", "Öndótt", "Ormgerthr", "Ormhildr", "Ósk", "Otkatla", "Raförta", "Ragnfrithr", "Ragnheithr", "Ragnhildr", "Rannlaug",
      "Rannveig", "Reginhlif", "Reginleif", "Reginthruthr", "Rjúpa", "Runfrithr", "Runhildr", "Sæhildr", "Salbjörg", "Salgerthr", "Sæuthr", "Signy", "Sigríthr", "Sigrunn",
      "Sigthruthr", "Sinn", "Snælaug", "Sólveig", "Sölvör", "Steinfrithr", "Steingerthr", "Steinhildr", "Steinunn", "Steinvör", "Svana", "Svanhildr", "Svanlaug",
      "Thjóthgerthr", "Thjóthhildr", "Thóra", "Thórarna", "Thorbjörg", "Thórdís", "Thórelfr", "Thórey", "Thorfinna", "Thorgerthr", "Thorgríma", "Thórhildr", "Thorkatla",
      "Thorlaug", "Thorleif", "Thorlót", "Thórny", "Thórodda", "Thórunn", "Thórvé", "Thórvör", "Thraslaug", "Thuríthr", "Tófa", "Úlfeithr", "Úlfhildr", "Úlfrún",
      "Valbjörg", "Valdís", "Valgerthr", "Védís", "Vefreyja", "Vefrithr", "Vélaug", "Vény", "Vigdís", "Vilborg", "Vilgerthr", "Yngvildr", "Yrr"};

inline vector<string> ElfMascFirstNames = {"Aedd", "Aelhaearn", "Aeron", "Afan", "Afon", "Amhar", "Amlawdd", "Amren", "Anarand", "Anarawd", "Aneirin", "Angwyn", "Anian",
      "Anwas", "Anwyl", "Arllechwedd", "Arthawd", "Arthien", "Arthwr", "Arvel", "Auryn", "Auwyn", "Avaon", "Barri", "Bedrawd", "Bedwin", "Bedwor", "Bedwyr", "Berwyn",
      "Blaen", "Blathaon", "Bleddyn", "Bledri", "Bradwen", "Bran", "Brathach", "Brychan", "Bryn", "Brynmor", "Brys", "Cadarn", "Cadawg", "Cadel", "Cadellin", "Cadfael",
      "Cadfan", "Cadlew", "Cadoc", "Cadreith", "Cadwaladr", "Cadwallon", "Cadwgawn", "Cadwr", "Cadwyr", "Cai", "Caradoc", "Caradog", "Carannog", "Carantoc", "Carnedyr",
      "Caw", "Cedifor", "Celyn", "Cenwyn", "Ceredig", "Ceri", "Cerwyn", "Cian", "Cledwyn", "Clydog", "Clywd", "Coed", "Coel", "Collen", "Corryn", "Culhwch", "Culvanawd",
      "Custennin", "Cynan", "Cynbel", "Cyndeyrn", "Cynfan", "Cynfarch", "Cynfor", "Cyngar", "Cynhaern", "Cynog", "Cynrain", "Cynwal", "Dallwyr", "Derwyn", "Digon", "Dilwyn",
       "Doged", "Dremidydd", "Drwst", "Drych", "Drydvas", "Dryw", "Duach", "Dyfan", "Dyfrig", "Dylan", "Dynand", "Dywel", "Edenewen", "Edern", "Ederyn", "Eidiol", "Eidyn",
       "Einion", "Eivyonydd", "Elfed", "Elfodd", "Elphin", "Elwyn", "Elystan", "Emhyr", "Emyr", "Ergyryad", "Ermid", "Eurosswydd", "Evnissyen", "Evrei", "Ffernfael", "Fflam",
       "Fflergant", "Fflewdwr", "Ffodor", "Gadwy", "Ganfael", "Garanhir", "Garanwyn", "Garym", "Geraint", "Gerwyn", "Gethin", "Gildas", "Glewlwyd", "Glyndwer", "Glywys",
       "Gogyvwlch", "Goreu", "Govan", "Granwen", "Gronw", "Gruffin", "Gruffudd", "Gruffydd", "Guital", "Gurhyr", "Gwalchmei", "Gwawl", "Gwern", "Gwilim", "Gwion", "Gwitart",
       "Gwyar", "Gwyddno", "Gwydion", "Gwyglet", "Gwynfardd", "Gwynn", "Gwyr", "Gwythyr", "Heilyn", "Hwfa", "Hyfaidd", "Hywel", "Iddawg", "Idenerth", "Idnerth", "Idris",
       "Idwal", "Illtyd", "Iona", "Iorwerth", "Iowerth", "Ithel", "Kelyn", "Kilwich", "Kilydd", "Kynon", "Kynwyl", "Laodegan", "Lleu", "Lleufer", "Lloyd", "Lludd", "Llwydeu",
       "Llygad", "Llyr", "Llywarch", "Llywelyn", "Mabon", "Mabsant", "Madern", "Madoc", "Maelgwn", "Maelon", "Maelwys", "Mahel", "March", "Math", "Mawr", "Medyr", "Meilyr",
       "Meneu", "Meredydd", "Merfyn", "Meriawn", "Mewan", "Morcan", "Myrddin", "Naw", "Nennoc", "Nerth", "Nerthach", "Nissyen", "Nudd", "Odyar", "Odyaw", "Olwydd", "Onllwyn",
       "Owein", "Padarn", "Peissawg", "Pendaran", "Peredur", "Pryderi", "Pwyll", "Ren", "Rhain", "Rheged", "Rhinfrew", "Rhodri", "Rhun", "Rhyawdd", "Rhydderch", "Rhys",
       "Riogoned", "Sedwei", "Seithennin", "Sel", "Selyf", "Senyllt", "Sugyn", "Sulgen", "Sulien", "Syvwlch", "Talfryn", "Taliesin", "Tarrant", "Tegvan", "Tegwared", "Teilo",
       "Teregud", "Teryrnon", "Trahaearn", "Treman", "Trevelyan", "Tringad", "Trystan", "Tudur", "Tudwal", "Tungyr", "Twrgadarn", "Tywysog", "Uchdryd", "Urien", "Uther",
       "Varwawc", "Vychan", "Wadu", "Wynn", "Ysgawyn", "Ystrwyth"};
inline vector<string> ElfFemmeFirstNames = {"Aanor", "Aderyn", "Adsiltia", "Adwen", "Aeronwy", "Agharat", "Almedha", "Angharad", "Angharat", "Angwen", "Anwyl", "Aregwedd",
"Arianwen", "Badellfawr", "Belisama", "Blodeuwedd", "Blodeyn", "Blodwen", "Brandgaine", "Brangwirin", "Branwen", "Brisen", "Cain", "Canda", "Ceinwen", "Ceri", "Cigfa",
"Coalaulin", "Cordula", "Coulava", "Creiddylad", "Creirwy", "Darerca", "Druantia", "Dwynwen", "Eiddwen", "Eira", "Eiralys", "Eirian", "Eirianwen", "Eirlys", "Eiron",
"Eirwen", "Eirwyn", "Eleri", "Elin", "Ellylw", "Eluned", "Elwy", "Elwyn", "Eneuawy", "Enid", "Ennogen", "Enrhydreg", "Eoghania", "Erdudfyl", "Esyllt", "Eurfron", "Eurneid",
"Eurwen", "Ewaesdah", "Eysllt", "Flamina", "Ganieda", "Gawrddyd", "Goewin", "Goleuddydd", "Goleudid", "Guaur", "Gwefr", "Gwen", "Gwenddyd", "Gwendolyn", "Gwendydd",
"Gweneal", "Gwenever", "Gwenhifar", "Gwenhwyfar", "Gwenhywach", "Gwenledyr", "Gwenllian", "Gwenlliant", "Gwennol", "Gwenog", "Gwladys", "Gwledyr", "Gwlithyn", "Gwylfai",
 "Hafren", "Hafwen", "Heulwen", "Igerna", "Indeg", "Innogen", "Lanshuil", "Llinos", "Luned", "Lynwen", "Mabyn", "Maelona", "Malvina", "Mederei", "Medhuil", "Medlan",
 "Meinwen", "Melangell", "Meleri", "Methahel", "Modwen", "Morfudd", "Morgant", "Morved", "Morwenna", "Nest", "Neued", "Nimue", "Nona", "Olwen", "Penarddun", "Rathtyen",
 "Regau", "Rhawn", "Rhedyn", "Rhiain", "Rhiannon", "Rhianwen", "Rhonwen", "Rhoswen", "Saeth", "Sirona", "Suilaliun", "Sulwyn", "Taghwystyl", "Tancoystl", "Tangustel",
 "Tangwen", "Tegan", "Tegau", "Tegwen", "Teleri", "Telyn", "Yseult"};

inline vector<string>  ElfLastNames= {"Ablach", "Áedammair", "Affraic", "Aíbinn", "Aideen", "Aífe", "Ailbe", "Aileann", "Ailleann", "Áine", "Almaith", "Anga", "Anlaith",
"Aodhnait", "Aoibheann", "Aróc", "Barrdub", "Be Bhionn", "Bé Fáil", "Bébhinn", "Bél", "Belocc", "Ben Mide", "Ben Muman", "Bil", "Brigid", "Brigit", "Cacht", "Caillech Domnaill",
"Caillech Finnen", "Cainnech", "Caíntigern", "Caírech", "Catan", "Cellach", "Chrodoara", "Ciannait", "Ciar", "Cingit", "Clothra", "Cnes", "Coblaith", "Cochrann", "Cocrich",
"Cóemfhind", "Coímell", "Colan", "Columba", "Conandil", "Concessa", "Conchend", "Conchenn", "Condal", "Congan", "Crínóc", "Cróeb", "Cuach", "Cumman", "Dailfind", "Dairine",
"Damhnait", "Dar Cárthaind", "Dearbháil", "Dearbhorgaill", "Dechtire", "Deirdriu", "Der Bforgaill", "Der Draigen", "Derbáil", "Dercco", "Derg", "Dianaim", "Doireand",
"Doirend", "Dron", "Dubchoblaig", "Dubh", "Dubh Essa", "Dubh Lacha", "Dubh Lemna", "Dubhchobhlaigh", "Dubhgilla", "Dúinsech", "Dúnlaith", "Eabha", "Eachraidh", "Eadain",
 "Echrad", "Éile", "Eilgri", "Eithne", "Elige", "Ellbríg", "Emer", "Érennach", "Ériu", "Etaín", "Ethne", "Etromma", "Euginia", "Failend", "Faílenn", "Faimdid", "Fainche",
 "Fedelm", "Feidelm", "Fiathnait", "Fína", "Finbil", "Find", "Findchóem", "Findétand", "Findscuap", "Fíne", "Finnecht", "Fionnabhair", "Flann", "Forbflaith", "Fuamnach",
 "Garb", "Gelgéis", "Gnathnad", "Gobnait", "Gormán", "Gormfhlaith", "Gormlaith", "Ibel", "Indécht", "Inderb", "Indiu", "Íte", "Lann", "Lasair", "Lassar", "Lassi", "Lathir",
 "Lebarcham", "Lerben", "Lerthan", "Lethann", "Lí Ban", "Liadan", "Lígach", "Luiseach", "Macha", "Máel Etich", "Máel Fabaill", "Máel Mide", "Máel Muire", "Martha", "Medb",
 "Meld", "Mincloth", "Móen", "Mongfhind", "Mór", "Mór Muman", "Muadhnait", "Mugain", "Muireann", "Muirecht", "Muirenn", "Muirgel", "Muiriath", "Muirin", "Muirne",
 "Narbflaith", "Ném", "Némdaille", "Nessa", "Niamh", "Óchae", "Óebfhinn", "Orlaith", "Órnat", "Ragnailt", "Ríoghnach", "Roach", "Rónnait", "Sadb", "Sadhbh", "Sáerlaith",
  "Samthann", "Saraid", "Sarnat", "Scathach", "Scáthdercc", "Sciath", "Sebdann", "Selblaith", "Sétach", "Sín", "Sinech", "Sithmaith", "Sodelb", "Sogáes", "Suaibsech",
   "Táethen", "Tailefhlaith", "Taileflaith", "Tailltiu", "Téiti", "Temair", "Tlachtga", "Tómnat", "Tuathflaith", "Uaithne", "Uallach", "Uasal", "Uathach"};

inline vector<string> DragonbornFirstNames = {"Arjhan", "Balasa", "Bharash", "Donaar", "Ghesh", "Heskan", "Kriv", "Medrash", "Mehen", "Nadar", "Pandjed", "Patrin", "Rhogar",
"Shamash", "Shedinn", "Tarhun", "Torinn", "Akra", "Biri", "Daar", "Farideh", "Harann", "Havilar", "Jheri", "Kava", "Korinn", "Mishann", "Nala", "Perra", "Raiann", "Sora",
 "Surina", "Thava", "Uadjit"};

 inline vector<string> DragonbornLastNames = {"Clethtinthiallor", "Daardendrian", "Delmirev", "Drachedandion", "Fenkenkabradon", "Kepeshkmolik", "Kerrhylon,Kimbatuul",
 "Linxakasendalor", "Myastan", "Nemmonis", "Norixius", "Ophinshtalajiir", "Prexijandilin", "Shestendeliathm", "Turnuroth", "Verthisathurgiesh", "Yarjerit"};

inline vector<string> GiffFemmeFirstnames = {"Adélaïde", "Adèle", "Adeline", "Adorée", "Adrienne", "Agathe", "Agnès", "Aimée", "Alexandra", "Alexia", "Alice",
 "Alicia", "Aline", "Alison", "Alphonsine", "Amandine", "Amarante", "Ambre", "Amélie", "Anaëlle", "Anaïs", "Andréa", "Andrée", "Angèle", "Angeline", "Angelique",
 "Anna", "Anne", "Anne- Louise", "Anne-Marie", "Annette", "Antoinette", "Apolline", "Arianne", "Arienne", "Arlette", "Aude", "Audrey", "Aurélie", "Aurore", "Avril",
 "Axelle", "Barbara", "Béatrice", "Bénédicte", "Benjamine", "Benoite", "Bernadette", "Bernardine", "Berthe", "Blanche", "Brigitte", "Camille", "Carine", "Carla", "Carole",
  "Caroline", "Cassandra", "Catherine", "Cécile", "Céleste", "Célestine", "Célia", "Céline", "Cerise", "Chantal", "Chanté", "Charline", "Charlotte", "Chloé", "Christelle",
  "Christine", "Claire", "Clara", "Clarisse", "Claudette", "Claudine", "Clémence", "Clementine", "Cloé", "Clothilde", "Colette", "Coline", "Constance", "Coralie", "Corinne",
  "Cosette", "Danièle", "Danielle", "Delphine", "Denise", "Désirée", "Diane", "Dianne", "Dieudonnée", "Dominique", "Donatienne", "Doriane", "Dorothée", "Edwige", "Eléonore",
   "Éliane", "Elisa", "Elisabeth", "Élise", "Élodie", "Eloise", "Elsa", "Emeline", "Émilie", "Emma", "Emmanuelle", "Esmée", "Estelle", "Esther", "Eugénie", "Eulalie", "Eva",
    "Eve", "Evette", "Fabienne", "Fabiola", "Fanny", "Faustine", "Félicie", "Felicienne", "Fernande", "Fifi", "Flavie", "Fleur-Aimée", "Florette", "Florianne", "Francine",
    "Françoise", "Frédérique", "Gabrielle", "Gaetane", "Geneviève", "Georgette", "Georgine", "Germaine", "Ghislain", "Ghislaine", "Gigi", "Gilberte", "Gisèle", "Giselle",
    "Gisselle", "Hannah", "Hélène", "Héloïse", "Henriette", "Hermine", "Honorine", "Hortense", "Hyacinthe", "Inès", "Irène", "Irénée", "Isabeau", "Isabelle", "Jacinthe",
    "Jacqueline", "Jade", "Jeanine", "Jeanne", "Jeannette", "Jeannine", "Jessica", "Joceline", "Joelle", "Jolie", "Josée", "Josèphe", "Joséphine", "Josette", "Josiane",
    "Judith", "Julia", "Juliane", "Julie", "Julienne", "Juliette", "Justine", "Kelly", "Kenza", "Laetitia", "Laura", "Laure", "Laure- Hélène", "Laurentine", "Laurette",
    "Laurie", "Laurine", "Léa", "Lena", "Léonie", "Léonne", "Léontine", "Liane", "Lisa", "Lise", "Lisette", "Lola", "Lou", "Louise", "Luce", "Lucie", "Lucienne", "Lucile",
    "Lucille", "Lucinde", "Lucrece", "Ludivine", "Lunete", "Lydie", "Madeleine", "Madeline", "Maelle", "Maeva", "Manon", "Marceline", "Marcelle", "Marcellette",
    "Marcelline", "Margaux", "Margot", "Marguerite", "Marie", "Marie-Anne", "Marie-Claire", "Marie-Françoise", "Marie-Hélène", "Marie-Léonie", "Marie-Thérèse", "Marielle",
    "Mariette", "Marina", "Marine", "Marion", "Marise", "Marthe", "Martine", "Mathilde", "Maximilienne", "Mélanie", "Mélisande", "Mélissa", "Michèle", "Micheline",
    "Michelle", "Mignon", "Mirabelle", "Mireille", "Monique", "Morgane", "Muriel", "Myriam", "Nadia", "Nadine", "Natalie", "Nathalie", "Nicole", "Nicolette", "Nina",
     "Ninette", "Ninon", "Noella", "Noelle", "Noémie", "Oceane", "Odette", "Odile", "Olympe", "Ophélie", "Oriane", "Orianne", "Ouida", "Pascale", "Pascaline", "Paule",
     "Paulette", "Pauline", "Perrine", "Philippine", "Placide", "Rachel", "Raymonde", "Rébecca", "Régine", "Reine", "Renée", "Rochelle", "Rolande", "Romaine", "Romane",
     "Rosalie", "Rose", "Rose-Lucie", "Roselle", "Rosemonde", "Rosette", "Rosine", "Roxane", "Roxanne", "Sabine", "Salomé", "Sandrine", "Sarah", "Seraphine", "Sévérine",
     "Sidonie", "Solange", "Solène", "Sophie", "Stéphanie", "Suzanne", "Suzette", "Sybille", "Sylvaine", "Sylvia", "Sylviane", "Sylvianne", "Sylvie", "Tatienne", "Thérèse",
     "Toinette", "Valentine", "Valérie", "Véronique", "Victoire", "Victoria", "Victorine", "Vienne", "Violette", "Vivienne", "Yolande", "Yseult", "Yvette", "Yvonne",
     "Zephyrine", "Zézette", "Zoé"};

inline vector<string> GiffMascFirstNames = {"Abel", "Absolon", "Achille", "Adam", "Adolphe", "Adrien", "Aimé", "Alain", "Alan", "Albert", "Alex", "Alexandre",
    "Alexis", "Alfred", "Allan", "Alphonse", "Ambroise", "Amédée", "Anatole", "André", "Anselme", "Anthony", "Antoine", "Antonin", "Aristide", "Armand", "Arnaud",
    "Arsène", "Arthur", "Auguste", "Augustin", "Aurèle", "Aurelien", "Axel", "Aymeric", "Baltasar", "Baptiste", "Barnabé", "Barthélémy", "Basile", "Bastien", "Baudouin",
    "Benjamin", "Benoit", "Bernard", "Bertrand", "Blaise", "Boniface", "Brice", "Bruno", "Bryan", "Cédric", "Célestin", "Cesaire", "César", "Charles", "Charles-Henri",
    "Christian", "Christophe", "Christopher", "Claude", "Clément", "Colombain", "Constant", "Constantin", "Corentin", "Corin", "Damien", "Daniel", "David", "Denis",
    "Dennis", "Désiré", "Didier", "Dieudonné", "Dimitri", "Diodore", "Dion", "Donat", "Donatien", "Dorian", "Dylan", "Edgar", "Edgard", "Edmond", "Édouard", "Eloi",
    "Émile", "Émilien", "Emon", "Enzo", "Eric", "Erwan", "Étienne", "Eugène", "Eustache", "Évariste", "Evrard", "Fabien", "Fabrice", "Felicien", "Félix", "Ferdinand",
    "Fernand", "Fiacre", "Firmin", "Florent", "Florentin", "Florian", "François", "Frédéric", "Gabriel", "Gaétan", "Gaspard", "Gaston", "Gautier", "Geoffroi", "Georges",
    "Gérald", "Gérard", "Géraud", "Germain", "Gervais", "Gilbert", "Gilles", "Godelieve", "Gratien", "Grégoire", "Guillame", "Guillaume", "Gustave", "Guy", "Hector",
    "Henri", "Herbert", "Hercule", "Hervé", "Hilaire", "Honoré", "Horace", "Hubert", "Hugo", "Hugues", "Humbert", "Ignace", "Iréné", "Isidore", "Jacques", "Jacques-Yves",
    "Jason", "Jean", "Jean-Baptiste", "Jean-Charles", "Jean-Claude", "Jean-Jacques", "Jean-Louis", "Jean-Luc", "Jean-Marie", "Jean-Michel", "Jean-Paul", "Jean-Pierre",
    "Jean-Yves", "Jérémie", "Jérémy", "Jérôme", "Joachim", "Joël", "Jonathan", "Jordan", "Joseph", "Josue", "Jourdain", "Jules", "Julien", "Juste", "Justin", "Kevin",
    "Kilian", "Killian", "Lambert", "Laurent", "Lazare", "Léandre", "Léo", "Léon", "Léonard", "Léonce", "Léopold", "Lilian", "Lionel", "Loic", "Lothaire", "Louis",
    "Loup", "Luc", "Lucas", "Lucien", "Mael", "Marc", "Marc-Antoine", "Marcel", "Marcellin", "Marin", "Marius", "Martin", "Mathias", "Mathieu", "Mathis", "Mattéo",
    "Matthieu", "Maurice", "Maxence", "Maxime", "Maximilien", "Mehdi", "Michel", "Mickaël", "Modestine", "Mohamed", "Narcisse", "Nathan", "Nazaire", "Nicholas",
    "Nicodème", "Nicolas", "Noé", "Noel", "Odilon", "Olivier", "Onesime", "Papillion", "Pascal", "Paschal", "Patrice", "Patrick", "Paul", "Perceval", "Philbert",
    "Philibert", "Philippe", "Pierre", "Pons", "Prosper", "Quentin", "Rainier", "Raoul", "Raphaël", "Raymond", "Régis", "Rémi", "Rémy", "Renard", "Renaud", "René",
    "Reynaud", "Richard", "Robert", "Robin", "Roch", "Rodolph", "Rodolphe", "Rodrigue", "Roger", "Roland", "Romain", "Ryan", "Sacha", "Samuel", "Sébastien", "Serge",
    "Séverin", "Simon", "Sofiane", "Stéphane", "Steven", "Sylvain", "Sylvestre", "Tanguy", "Theirn", "Théo", "Théodore", "Théophile", "Thibaud", "Thibault",
    "Thibaut", "Thierry", "Thomas", "Timothée", "Tom", "Tony", "Toussaint", "Tristan", "Ulrich", "Urbain", "Valentin", "Valère", "Valéry", "Vespasien", "Victor",
    "Vincent", "Virgile", "William", "Xavier", "Yanis", "Yann", "Yannic", "Yves", "Yvon"};

inline vector<string> GiffLastnames = {"Abelin", "Abiven", "Abrioux", "Agenet", "Aignan", "Alaize", "Alary", "Allain", "Allaire", "André", "Andrieux", "Andrus", "Angot",
"Apavou", "April", "Armand", "Arpin", "Arsenault", "Asselin", "Aubé", "Aubert", "Aubier", "Aubron", "Aubry", "Auclair", "Audette", "Audinot", "Aurillac", "Auvinet",
"Avare", "Ayrault", "Babineaux", "Bachelot", "Bachere", "Bacquet", "Baguet", "Balladur", "Bardet", "Baroin", "Barrière", "Barrot", "Bascou", "Bassot", "Bataille",
"Bauché", "Baumel", "Bazaine", "Béart", "Beauchamps", "Beaudry", "Beaulieu", "Beausoleil", "Becquerel", "Bédard", "Bégin", "Béland", "Bélanger", "Bellemare", "Benoit",
"Béraud", "Bergelin", "Bergerat", "Bernard", "Bernier", "Berthiaume", "Bertholet", "Bertrand", "Besson", "Bibeau", "Bienvenu", "Biessy", "Billard", "Billardon", "Binet",
 "Birraux", "Biset", "Bizier", "Blais", "Blanc", "Blanchard", "Bloche", "Blondeau", "Bochart", "Boileau", "Bois", "Boisseau", "Boisserie", "Boisvin", "Boncoeur", "Bonneau",
 "Bonnet", "Bonrepaux", "Bordelon", "Bosson", "Bottereau", "Bouchard", "Boucher", "Boucheron", "Boudreaux", "Bouisault", "Boulanger", "Boulard", "Bourchier", "Bourgeois",
 "Bourget", "Bousquet", "Boutin", "Bouvard", "Brangeard", "Bressand", "Breton", "Briand", "Brillard", "Brisson", "Broussard", "Brulé", "Brun", "Bussiere", "Cacheux",
 "Cailler", "Calmat", "Capet", "Cardot", "Carmouche", "Caron", "Carré", "Carriere", "Cartier", "Cassou", "Catineau", "Cavaillé", "Cazeneuve", "Chabert", "Chabot",
 "Chaillé", "Chambon", "Chapais", "Charasse", "Charé", "Charette", "Charié", "Charles", "Charpentier", "Charron", "Chartier", "Chassé", "Chatelain", "Chaussé", "Chauveau",
  "Chazal", "Chenard", "Cherioux", "Chevalier", "Chevallier", "Cheysson", "Cleary", "Clément", "Cleron", "Cloutier", "Cochet", "Collange", "Comeau", "Corond", "Coté",
  "Couderc", "Coulomb", "Courtois", "Cousteau", "Coustier", "Couture", "Cressac", "Cros", "Cyr", "d’Aubert", "Dagenais", "Daniel", "Darthere", "Dasseux", "Daubresse",
  "Dauge", "Dauvergne", "Dauzat", "David", "de Charette", "de Courson", "de la Nord", "de Laleuf", "de Louche", "de Mearau", "de Mornay", "de Panafieu", "de Robien",
   "de Ronsard", "de Rosny", "de Villiers", "Deblois", "Decaudin", "Defontaine", "Degauchy", "Dehaine", "Dejean", "Delambre", "Delebarre", "Delibes", "Delumeau", "Demay",
    "Demers", "Deniaud", "Denis", "Denise", "Deprez", "Derosier", "Deschamps", "Deschenes", "Desorcy", "Desrosiers", "Desvaux", "Devaud", "Devoe", "Dion", "Dionne",
    "Doiron", "Doré", "Doucet", "Douyère", "Dreyfus", "Dubois", "Dubroc", "Ducharme", "Ducote", "Dufaure", "Dugas", "Duhamel", "Dumont", "Dupéré", "Dupont", "Dupré",
    "Dupuis", "Durand", "Durieux", "Duron", "Dusserre", "Egert", "Estienne", "Evin", "Fabre", "Facon", "Faichaud", "Faucher", "Faure", "Ferland", "Ferrand", "Filleul",
    "Fleury", "Fontaine", "Forissier", "Fortier", "Foucault", "Foucher", "Fournier", "Françaix", "François", "Frêche", "Frederic", "Fremont", "Fréneau", "Fromion",
    "Gabillon", "Gabrignon", "Gachard", "Gaillard", "Galeppe", "Gamache", "Ganneau", "Gantier", "Garceau", "Garcia", "Garneau", "Garnier", "Garrigues", "Gaubert",
    "Gauchier", "Gaudeau", "Gaudet", "Gaulin", "Gauthier", "Gautier", "Gauvin", "Généreux", "Genin", "Gentille", "Gérard", "Gervais", "Gilbert", "Girard", "Giraud",
     "Giroux", "Godfrain", "Godin", "Gosselin", "Goudeau", "Goulard", "Goulet", "Gouriou", "Gourrier", "Gousse", "Gouzes", "Grasset", "Grégoire", "Grenier", "Grignon",
     "Grimault", "Grondin", "Guédon", "Guérin", "Guichon", "Guidault", "Guillemain", "Guillet", "Guyard", "Hachée", "Hamel", "Hascoët", "Hébert", "Hélion", "Hellier",
     "Henry", "Herault", "Hériaud", "Hermier", "Hervé", "Hollande", "Houde", "Houellebecq", "Houle", "Huppé", "Huwart", "Idrac", "Imbert", "Jacquemart", "Jacques",
     "Janquin", "Jette", "Joffre", "Jolicoeur", "Joliot", "Jouhanin", "Juneau", "Juppé", "L’anglais", "L’heureux", "L’hiver", "Labarre", "Labauve", "Labbé", "Labelle",
    "Laborde", "Labrecque", "Lacasse", "Lachance", "Lacour", "Lacroix", "Lafleur", "Lafontaine", "Laforest", "Laforge", "Laframboise", "Lagrange", "Lajeunesse", "Lajoie",
    "Lalande", "Lambert", "Lamontagne", "Lamour", "Lanctot", "Langelier", "Langevin", "Langlais", "Lapierre", "Laporte", "Laroux", "Laurent", "le Bris", "le Chat",
    "le Chevallier", "le Roux", "le Roy", "le Vern", "Lebel", "Leblanc", "Lebrun", "Leclerc", "Ledoux", "Leduc", "Lefait", "Lefèbvre", "Lefèvre", "Lefort", "Legault",
    "Legrand", "Lejeune", "Lemaitre", "Lemieux", "Lemoine", "Lenoir", "Léotard", "Lepage", "Lequiller", "Leroux", "Leroy", "Lessard", "Létourneau", "Leveillé",
    "Levert", "Levesque", "Lopez", "Louet", "Louis", "Lussier", "Machault", "Madelin", "Madrelle", "Malon", "Marceau", "Marcellin", "Marchand", "Marché", "Marié",
    "Marier", "Marin", "Mariot", "Marlin", "Marot", "Marquis", "Marteau", "Martin", "Martinez", "Masse", "Massillon", "Masson", "Mathieu", "Mathus", "Maubois",
    "Maurer", "Mazuret", "Ménard", "Mercier", "Meriot", "Métadier", "Métais", "Michaud", "Michel", "Michon", "Migaud", "Mignon", "Millon", "Mondet", "Monjeau",
    "Montané", "Montebourg", "Moreau", "Morel", "Morency", "Morin", "Motté", "Mouton", "Müller", "Muselier", "Nadeau", "Napert", "Narquin", "Nauche", "Nayral",
    "Néricault", "Neveu", "Nicolas", "Nicolin", "Nisard", "Normand", "Olier", "Olivier", "Ouellette", "Outin", "Paillé", "Pajon", "Pandraud", "Papineau", "Paquet",
    "Paquin", "Paradis", "Paré", "Paul", "Peillon", "Pelchat", "Pélissard", "Pelletier", "Pépin", "Péricard", "Pérol", "Perreault", "Perrin", "Pery", "Petit",
    "Petrie", "Picard", "Pingault", "Poiret", "Poissonnier", "Pons", "Pontier", "Pouchard", "Poulin", "Prejean", "Proulx", "Provencher", "Prudhomme", "Querard",
    "Quessy", "Quilès", "Rabethe", "Racicot", "Racine", "Raimond", "Rancourt", "Ratté", "Rebillard", "Recours", "Régis", "Renaudel", "Reny", "Reynaud", "Ribault",
    "Richard", "Richer", "Rideau", "Rigal", "Rigaud", "Rimbert", "Robert", "Robillard", "Robin", "Roche", "Rochefort", "Rochier", "Rodet", "Roi", "Rollet", "Rouger",
    "Rouleau", "Rouquet", "Rousseau", "Roussel", "Routhier", "Roux", "Ruel", "Sabourin", "Sainte-Marie", "Salles", "Sandrier", "Sarre", "Saunier", "Sauvadet",
    "Séguin", "Serra", "Sève", "Sibille", "Simard", "Simon", "St Crois", "St Germain", "St Pierre", "Suchet", "Taittinger", "Tallien", "Tanguay", "Tassin",
    "Tavernier", "Tercier", "Terrasse", "Tessier", "Tété", "Théberge", "Theriot", "Therrien", "Thibault", "Thibodet", "Thivierge", "Thomas", "Thoreau",
    "Tisserand", "Touchette", "Toulouse", "Touraine", "Trupin", "Turcotte", "Vachet", "Vachon", "Vaillancourt", "Valente", "Valleix", "Vasseur", "Vauzelle",
    "Vaxès", "Vegnault", "Veilleux", "Vergnier", "Vérien", "Vernaudon", "Verreau", "Vertefeuille", "Veyret", "Vézien", "Vidalies", "Viens", "Villeneuve",
    "Vincent", "Viollet", "Voisin", "Vuillaume", "Yvon"};

inline vector<string> GnomeFirstNames = {"Adan", "Adva", "Aiko", "Amorette", "Aripine", "Armida", "Belita", "Bonita", "Brenna", "Brooke", "Bingles", "Banxi",
"Bink", "Banli", "Bitsy", "Bitty", "Bixi", "Carlin", "Charlene Celqys", "Carnoa", "Darra", "Demi", "Dinky", "Elfi", "Flimp", "Giggbert", "Half-Pint",
 "Herble", "Helna", "Hisxif"};

inline vector<string>  GnomeLastNames = {"Dustseeker", "Nuttlattle", "Bernifitlacks", "Ipswoms", "Pelletsniffer", "Tinkerfoo", " Gemhair",
"Blaesocket", "Sabblewloth", "Muwlebra", "Giobibaar", "Woh", "Apleldosp", "Mirlon", "Peedlupnon"};

inline vector<string> GoblinFemmeFirstNames = {"Amu", "Aija", "Aila", "Aili", "Aina", "Aini", "Ainikki", "Aino", "Aira", "Airi", "Alli",
"Amanda", "Anna", "Anneli", "Anni", "Anniina", "Annikki", "Ansa", "Anu", "Arja", "Armi", "Asla", "Asta", "Auli", "Aulikki", "Aurora",
"Eija", "Eila", "Eine", "Eini", "Eira", "Elina", "Ella", "Emilia", "Emma", "Enni", "Erja", "Erkka", "Essi", "Eveliina", "Hanna", "Heini",
 "Helena", "Hellevi", "Helli", "Helmi", "Helvi", "Henna", "Heta", "Hilja", "Hilkka", "Hilla", "Hille", "Hillevi", "Hilma", "Iida", "Ilma",
 "Ilmatar", "Ilmi", "Ilta", "Immi", "Impi", "Inari", "Inka", "Inkeri", "Irja", "Iro", "Jasmin", "Jatta", "Jenna", "Jenni", "Johanna", "Jonna",
"Julia", "Kaarina", "Kaino", "Kaisa", "Kanerva", "Karoliina", "Kastehelmi", "Katariina", "Kielo", "Kristiina", "Kukka", "Kylli", "Kyllikki", "Lahja",
"Laina", "Laura", "Lemmikki", "Lempi", "Liisa", "Lumi", "Lumikki", "Lyyli", "Maiju", "Maikki", "Maila", "Maili", "Mailis", "Maini", "Manta", "Maria",
"Marjatta", "Marjo", "Marjukka", "Marjut", "Mattila", "Meeri", "Meri", "Merja", "Mervi", "Mia", "Mielikki", "Miia", "Miimu", "Milja", "Milla", "Mimmi",
"Minna", "Minttu", "Mira", "Mirja", "Mirka", "Mirkka", "Mirva", "Nea", "Noora", "Oili", "Oivi", "Onerva", "Oona", "Orvokki", "Osma", "Outi", "Pälvi",
"Pilvi", "Pinja", "Pirita", "Piritta", "Pulmu", "Raija", "Raila", "Raili", "Raisa", "Raita", "Rauha", "Rauna", "Rauni", "Reija", "Riina", "Riita", "Ritva",
"Roosa", "Ruusu", "Saana", "Saija", "Saila", "Saima", "Saimi", "Saini", "Sanelma", "Sani", "Sanna", "Sanni", "Sara", "Satu", "Seija", "Selja", "Senja", "Senni",
"Siiri", "Sini", "Sinikka", "Sirja", "Sirke", "Sirkka", "Sirkku", "Sirpa", "Sisko", "Sivi", "Sofia", "Sohvi", "Soila", "Soile", "Soili", "Sointu", "Solja",
"Sorja", "Suila", "Suometar", "Susanna", "Suvi", "Taija", "Taimi", "Taina", "Talvikki", "Tarja", "Taru", "Teija", "Tellervo", "Terhi", "Terhikki",
"Terttu", "Titta", "Toivo", "Tuija", "Tuire", "Tuomi", "Tuovi", "Tutta", "Tuttu", "Tuukka", "Tuula", "Tuuli", "Tuulia", "Tuulikki", "Tuure", "Tyni",
"Tytti", "Tyyne", "Tyyni", "Ulla", "Ulpu", "Unelma", "Uolevi", "Usko", "Uula", "Valma", "Valpuri", "Vanamo", "Vappu", "Varma", "Varpu", "Vaula", "Veera",
"Vellamo", "Venla", "Viena", "Vieno", "Virpi", "Virva", "Virve", "Vuokko"};

inline vector<string>  GoblinMascFirstNames = {"Aalto", "Aapo", "Aappo", "Aarre", "Aarto", "Aatos", "Aatto", "Aatu", "Ahti", "Ahto", "Ahvo", "Aimo", "Aki",
"Aku", "Albert", "Ale", "Aleksi", "Ali", "Alpi", "Alpo", "Altti", "Ano", "Antero", "Antti", "Arhippa", "Arho", "Ari", "Armas", "Arsi", "Arttu", "Arvi",
"Arvo", "Asko", "Asmo", "Atro", "Atso", "Atte", "Auno", "Auvo", "Bengt", "Eemeli", "Eetu", "Eikki", "Elias", "Ensio", "Esko", "Hannu", "Heikki", "Heimo", "Henrik",
"Herkko", "Hiski", "Iikka", "Iiri", "Iiro", "Ilkka", "Ilmari", "Ilmo", "Ilpo", "Ilppo", "Into", "Isko", "Ismo", "Isto", "Jalmari", "Jalo", "Jami", "Jari", "Jarkko",
"Jarko", "Jarmo", "Jarno", "Jere", "Jesse", "Johannes", "Joni", "Joona", "Joonas", "Jori", "Jouko", "Jouni", "Jouo", "Juha", "Juhani", "Juho", "Jukka", "Juska", "Juuso",
"Jyri", "Jyrki", "Kaj", "Kalervo", "Kaleva", "Kalevi", "Kalle", "Kari", "Karri", "Kauko", "Kauno", "Kauto", "Keijo", "Keimo", "Kerkko", "Kimmo", "Kristian", "Kuisma",
"Kullervo", "Lalli", "Lassi", "Lauri", "Leevi", "Lyly", "Mainio", "Manne", "Manu", "Markus", "Matias", "Matti", "Mauno", "Mies", "Mika", "Mikael", "Mikko", "Niko",
"Nuutti", "Nyyrikki", "Oiva", "Okko", "Olavi", "Onni", "Orvo", "Oskari", "Osmo", "Ossi", "Otso", "Panu", "Pasi", "Pekka", "Pellervo", "Pentti", "Petteri", "Pirkka",
"Pyry", "Raimo", "Rami", "Rauno", "Reima", "Reino", "Reko", "Reku", "Roope", "Sakari", "Saku", "Sampo", "Samppa", "Santeri", "Santtu", "Seppo", "Sipi", "Sippo", "Soini",
"Sulevi", "Sulho", "Sulo", "Tahvo", "Taisto", "Taito", "Tapani", "Tapio", "Tarmo", "Tarvo", "Tatu", "Teemu", "Teijo", "Tenho", "Teppo", "Terho", "Terjo", "Tero",
"Teuvo", "Toimi", "Toivo", "Tomi", "Touko", "Tuomas", "Turkka", "Turo", "Tuukka", "Tuure", "Ukko", "Uljas", "Untamo", "Unto", "Uolevi", "Uoti", "Urho", "Urmas", "Urpo",
"Uuno", "Väinämö", "Väinö", "Valio", "Valo", "Valtteri", "Veijo", "Veikko", "Veiko", "Veini", "Veli", "Vesa", "Ville", "Visa", "Voitto", "Ylermi", "Yrjänä"};

inline vector<string>  GoblinLastNames = {"Aakula", "Aaltonen", "Ahlapuro", "Ahtisaari", "Aikio", "Airikkala", "Alapassi", "Alatalo", "Aunula", "Carpelan", "Erkko",
"Haapajarvi", "Haapaniemi", "Haavikko", "Hakkinen", "Hakonen", "Halvari", "Hämäläinen", "Hännenen", "Hannila", "Harju", "Hartikainen", "Hästesko", "Hättönen",
"Heikkilä", "Heikkinen", "Heilimo", "Hinkkanene", "Hirvimäki", "Hirvonen", "Huhtamo", "Huovinen", "Hurskainen", "Husu", "Hynninen", "Iiasalo", "Immonen", "Irjala",
"Isosomppi", "Isotalo", "Jaatinen", "Jänne", "Jarvilehto", "Järvinen", "Jeskanen", "Juteini", "Kaakinen", "Kääriänen", "Kallela", "Kallionkieli", "Kaltiainen",
"Kanniainen", "Kapanen", "Karhu", "Karila", "Karppinen", "Karsikas", "Karttunen", "Karvonen", "Kekkonen", "Kellomäki", "Kikkunen", "Kilpinen", "Kivelä", "Kiveli",
"Kivi", "Kivimaki", "Koistinen", "Koivisto", "Koivosto", "Koivu", "Koivula", "Kokko Kohva", "Koli", "Kononen", "Koppala", "Korhonen", "Koskinen", "Koskio", "Kuikkonen",
"Kukkamo", "Kumpula", "Kuusi", "Kuusisto", "Kytönen", "Laakkonen", "Lahtela", "Laine", "Lajunen", "Lammasniemi", "Lappi", "Lassila", "Laukkonen", "Lavonen", "Lehto",
"Lehväslaiho", "Leskinen", "Linna", "Linnankivi", "Lipponen", "Lönrot", "Lumiala", "Luukkonen", "Määttä", "Mäenpää", "Mäkelä", "Mäkilä", "Mäkinen", "Makkonen", "Malinen",
"Mannermaa", "Manninen", "Markula", "Melakoski", "Merikanto", "Merikken", "Mikkola", "Murtosaari", "Muttilainen", "Myllyniemi", "Näränen", "Narhi", "Nieminen", "Niilola",
"Nikkanen", "Noronen", "Nurkka", "Nurmii", "Ojanen", "Orasmaa", "Paakkonen", "Paasikivi", "Pakkarinen", "Palonen", "Parkkinen", "Peltosaari", "Peurajärvi", "Pietilä",
"Piironen", "Pimiä", "Pöljänen", "Poutiainen", "Pöyhtäri", "Pykkonen", "Rahnasto", "Räihä", "Raikkonen", "Rantamäki", "Raunio", "Reema", "Rekiaro", "Riekkinen",
"Rikkinen", "Rintala", "Ronkainen", "Rönkkö", "Ruoho", "Ryti", "Saari", "Saarinen", "Saintula", "Sallinen", "Salojärvi", "Salomäki", "Salonen", "Sarpaneva", "Sarri",
"Siilasvuo", "Sillanpää", "Sinkonnen", "Sirkiä", "Sirola", "Soimakallio", "Sookari", "Suomalainen", "Suviala", "Taitto", "Takala", "Talonen", "Talvela", "Tapionlinna",
"Tiainen", "Tiihonen", "Tiilikainen", "Tiuraniemi", "Toiviainen", "Tuominen", "Tuomioja", "Tykkylainen", "Uurainen", "Uusitalo", "Vaahtera", "Vaaraniemi", "Vacca",
"Vähätalo", "Vaijärvi", "Väinöla", "Vallinen", "Valtari", "Vänskä", "Varjo", "Varonen", "Veintie", "Verkko", "Viitasalo", "Vilhu", "Vilkuna", "Virén", "Virjonen",
"Virtanen", "Vuoti", "Wirkkala", "Yrjö"};

inline vector<string> HalflingFemmeFirstNames = {"Adain", "Aderyn", "Adwen", "Aeronwen", "Alison", "Alys", "Amanda", "Angharad", "Ann", "Anna", "Annest", "Annwyl",
 "Anwen", "Anwyl", "Aranwen", "Arian", "Ariana", "Arianwen", "Arwenna", "Arwyn", "Aylwen", "Barbara", "Beatrice", "Bethan", "Betrys", "Blanceflor", "Blodwen", "Blodwin",
"Blodwyn", "Brangwen", "Branwen", "Briant", "Bronwen", "Brynn", "Cadi", "Cari", "Caris", "Carol", "Caron", "Caryl", "Carys", "Cate", "Cath", "Cati", "Catrin", "Ceinwen",
"Ceinwin", "Ceri", "Cerys", "Christine", "Ciara", "Claire", "Clarisse", "Cordelia", "Corry", "Deborah", "Del", "Delia", "Delwen", "Delwin", "Delwyn", "Delyth","Deryn",
"Dierdre", "Dylis", "Dyllis", "Eifiona", "Eiluned", "Eira", "Eiralys", "Eirawyn", "Eirian", "Eiriol", "Eirlys", "Eirwen", "Elaine", "Elen", "Eleri", "Elin", "Eluned",
"Emma", "Enfys", "Enid", "Enit", "Ermin", "Essyllt", "Ffion", "Gaenor", "Gaynor", "Gemma", "Gladys", "Glenda", "Glenys", "Glynis", "Guenevere", "Guinevere", "Gwen",
"Gwenda", "Gwendolen", "Gwendolyn", "Gwenevere", "Gwenhwyfar", "Gwenllian", "Gwenlliana", "Gwladys", "Gwyneth", "Hafwen", "Helen", "Heulwen", "Hywela", "Idelle",
"Iestin", "Iola", "Isolde", "Jacqueline", "Jane", "Janet", "Jennifer", "Jestina", "Joanne", "Julie", "Justina", "Karen", "Katharine", "Kelly", "Laura", "Lewelyth",
"Linda", "Lisa", "Llewelydd", "Llinos", "Llio", "Llion", "Lona", "Lora", "Lowri", "Lowry", "Lynwen", "Mabli", "Maelona", "Mai", "Maillt", "Mair", "Mairona", "Mairwen",
"Mali", "Marared", "Mared", "Margaid", "Margaret", "Marged", "Maud", "Mega", "Megan", "Meghan", "Meira", "Meiriona", "Meirionwen", "Meironwen", "Meleri", "Meredith",
"Mererid", "Meriel", "Morgan", "Morwen", "Morwenna", "Myfanawy", "Myfanwy", "Myfi", "Myfina", "Nerys", "Nest", "Nesta", "Nia", "Nicola", "Olwen", "Owena", "Patricia",
"Petra", "Rachel", "Rebecca", "Rhiain", "Rhian", "Rhiannon", "Rhianwen", "Rhona", "Rhonda", "Rhonwen", "Rhosyn", "Ronwen", "Rowena", "Sarah", "Seren", "Sharon", "Sian",
"Siani", "Sioned", "Siwan", "Susan", "Taffia", "Taffine", "Tegwen", "Tracey", "Vanora", "Victoria", "Vivian", "Viviane", "Vivianne", "Viviene", "Vivienne", "Wenda",
"Winnifred", "Wynne", "Ysbail", "Yseult"};

inline vector<string> HalflingMascFirstNames = {"Alan", "Aled", "Alexander", "Alun", "Alwyn", "Alyn", "Ambrose", "Andras", "Andreas", "Aneirin", "Aneurin", "Arthur",
"Arwel", "Arwyn", "Asaph", "Awen", "Benedict", "Benet", "Berwyn", "Bevan", "Blaen", "Blair", "Blaire", "Blayre", "Bleddig", "Bleddyn", "Bradwen", "Brian", "Brinley",
"Broderick", "Bryn", "Brynach", "Brynley", "Brynmor", "Brynn", "Cade", "Cadel", "Cadogan", "Cadwgan", "Caerwyn", "Cai", "Caradoc", "Caradog", "Carr", "Carwyn", "Catesby",
"Cedig", "Cedric", "Cedrych", "Cemlyn", "Ceredig", "Ceri", "Charles", "Christopher", "Cledwyn", "Clyde", "Clywd", "Cole", "Colwyn", "Conwy", "Cyngen", "Cynstenian",
"Daff", "Dafi", "Dafydd", "Dai", "Daniel", "Darren", "David", "Dei", "Deian", "Deiniol", "Deinol", "Derwyn", "Dewey", "Dewi", "Dillan", "Dillon", "Dilwyn", "Donat",
"Drew", "Dru", "Dryw", "Dyfan", "Dylan", "Dynand", "Edar", "Eddow", "Edern", "Edmund", "Edmwnd", "Edryd", "Efan", "Eian", "Eifion", "Eignion", "Eilir", "Eilwyn", "Elfed",
"Elfodd", "Elgan", "Elian", "Elis", "Ellis", "Elwin", "Elwyn", "Elystan", "Emin", "Emlyn", "Emrys", "Eoin", "Ermel", "Ernan", "Errol", "Eryl", "Euan", "Eurig", "Euros",
"Evan", "Ewan", "Ewen", "Francis", "Galvin", "Garath", "Gareth", "Gary", "Gavin", "Gawain", "Geoffrey", "George", "Geraint", "Geriant", "Gerlad", "Gerwyn", "Gethen",
"Gethin", "Gilbert", "Glendower", "Glydwr", "Glyn", "Glynn", "Gowan", "Graham", "Gregory", "Griff", "Griffid", "Griffin", "Griffith", "Griffri", "Griffry", "Gruffudd",
"Gruffydd", "Gryffid", "Gryffri", "Gryffry", "Gryffyd", "Guilam", "Gwennarth", "Gwilim", "Gwilym", "Gwin", "Gwion", "Gwydion", "Gwylfai", "Gwyn", "Gwynfor", "Gwynne",
"Hadyn", "Hamon", "Harri", "Hefin", "Hew", "Heylin", "Hilary", "Howel", "Howell", "Hugh", "Humphrey", "Huw", "Hywel", "Iaco", "Iago", "Ian", "Ianto", "Idris", "Idriys",
"Idwal", "Iefan", "Iestin", "Iestyn", "Ieuan", "Ieuan Ifan", "Ievan", "Ifan", "Ifor", "Inir", "Ioan", "Iolo", "Iorewen", "Iorweth", "Iowan", "Isan", "Ithel", "Iwan",
"Jacob", "James", "Jenkin", "John", "Justin", "Kai", "Kane", "Kay", "Kedivor", "Keith", "Kened", "Keneth", "Kenneric", "Llew", "Llewelyn", "Lloyd", "Llud", "Llyr",
"Llywel Llywelyn", "Lowarch", "Lyn", "Lythan", "Mabon", "Maddox", "Madin", "Madoc", "Maldwyn", "Mark", "Marvin", "Math", "Matho", "Mathonwy", "Matthew", "Maugan",
"Maurice", "Melfyn", "Merddin", "Meredith", "Merfin", "Meriaun", "Merion", "Mervin", "Mervyn", "Meurig", "Meurik", "Michael", "Morfydd", "Morgan", "Morgant",
"Morven", "Morvin", "Morvran", "Mostyn", "Nai", "Neddig", "Nefydd", "Neilyn", "Neirin", "Nye", "Owain", "Owein", "Owen", "Padarn", "Patrick", "Paul", "Pedr",
"Penrod", "Penwyn", "Peredur", "Peter", "Pryderi", "Prydwen", "Pwyll", "Pyr", "Rees", "Reese", "Reis", "Rhett", "Rhisiart", "Rhobert", "Rhod", "Rhodri", "Rhys",
"Rhywallan", "Richard", "Robert", "Roland", "Rwrith", "Ryryd", "Samuel", "Searl", "Seiriol", "Selwyn", "Seren", "Siam", "Siarl", "Siôn", "Sionym", "Siors",
"Steffan", "Stephan", "Stephen", "Steven", "Sulien", "Sulwyn", "Tad", "Taff", "Taffy", "Talfryn", "Taliesin", "Tecwyn", "Tewdric", "Theodore", "Thomas", "Tom",
"Tomos", "Trahearn", "Trefor", "Trevor", "Tristan", "Trystan", "Tudor", "Tudur", "Tudyr", "Twm", "Uren", "Urien", "Valentine", "Vaughan", "Vaughn", "Walter",
"Watkin", "Wilim", "William", "Win", "Wmffre", "Wyn", "Wyndod", "Yago", "Yestin", "Yevan"};

inline vector<string> HalflingLastNames = {"Abadam", "Abernethy", "Abethell", "Abraham", "Adams", "Adda", "Alban", "Allen", "Andrews", "Annwyl", "Anthony", "Anwell",
"Anwill", "Anwyl", "Arnold", "Arthur", "Ash", "Ashe", "Ashton", "Astley", "Aston", "Atha", "Aubrey", "Austin", "Awbrey", "Babb", "Babbs", "Bach", "Badham", "Balch",
"Barry", "Batch", "Bateman", "Batha", "Bathoe", "Baugh", "Baughan", "Bawn", "Bayliss", "Baynham", "Beach", "Beavan", "Bebb", "Beddoe", "Beddoes", "Bedow", "Bedward",
"Bedwards", "Beedle", "Beethel", "Beinon", "Bellis", "Benbough", "Benbow", "Bengough", "Bengrisse", "Bengry", "Benjamin", "Bennet", "Bennett", "Bennion", "Bethall",
"Bethell", "Bevan", "Bevans", "Beynam", "Beynon", "Bibb", "Bidder", "Binnell", "Binner", "Bithell", "Blaeney", "Blaeny", "Blayney", "Blood", "Bloyd", "Blud", "Bolt",
"Bolter", "Bolver", "Bolvier", "Bond", "Bonsall", "Boulter", "Bound", "Bowdler", "Bowen", "Bown", "Brace", "Breese", "Breeze", "Brickstock", "Bridgestock", "Broderick",
"Bron", "Brook", "Brooks", "Brown", "Brun", "Bryn", "Bryse", "Bryste", "Bunnell", "Bunner", "Button", "Bydder", "Byddir", "Bynyr", "Bythell", "Byther", "Caddick",
"Caddock", "Cadwalader", "Cadwalidwr", "Caentwn", "Caffyn", "Cardiff", "Cardigan", "Carduggan", "Carew", "Caunton", "Charles", "Clayton", "Cleaton", "Clement",
"Cletton", "Coade", "Cole", "Connick", "Conway", "Conwy", "Coslett", "Cosslett", "Craddock", "Creese", "Crichett", "Cronne", "Crowther", "Crunn", "Cule", "Cull",
"Dackins", "Dai", "Daniel", "Daniels", "Daukyn", "Davenold", "David", "Davies", "Davis", "Dawes", "Dawkins", "Dawson", "Daykin", "Daykyn", "Deakyn", "Dee", "Devenallt",
"Devonald", "Dew", "Dodd", "Duggan", "Dykins", "Eddow", "Edmunds", "Edwards", "Elias", "Elis", "Ellice", "Ellis", "Emanuel", "Emont", "Ethell", "Evan", "Evans",
"Eynion", "Felix", "Fennah", "Fenner", "Flood", "Foulkes", "Gadarn", "Gainor", "George", "Gethin", "Gething", "Gibb", "Gibbon", "Gibbs", "Gibby", "Giles", "Gittings",
"Gittins", "Gittoes", "Goch", "Goff", "Gogh", "Goodge", "Goodin", "Goodwin", "Goodwyn", "Goudge", "Gough", "Gravenor", "Greenaway", "Greenhow", "Gregory", "Griffies",
"Griffin", "Griffis", "Griffith", "Griffiths", "Gronow", "Gruffydd", "Grunna", "Grunnah", "Guilt", "Guy", "Gwatkin", "Gwenlan", "Gwilliam", "Gwilt", "Gwinnett",
"Gwyn", "Gwynett", "Gwynn", "Gwynne", "Gwyther", "Haggar", "Haines", "Hamer", "Harries", "Harris", "Harry", "Hatfeld", "Hatfield", "Havard", "Hendry", "Henry",
"Henrys", "Herbert", "Herward", "Heyns", "Hier", "Hillin", "Hodgkin", "Hoel", "Hoell", "Hoells", "Hoesgyn", "Hole", "Holl", "Hopkin", "Hopkins", "Hoskin",
"Hoskins", "Hoskyn", "How", "Howard", "Howel", "Howell", "Howells", "Howes", "Hughes", "Humphrey", "Humphreys", "Husband", "Huws", "Hyer", "Hywel", "Iefan",
"Ifan", "Isans", "Ithel", "Jacob", "Jacobs", "James", "Jankin", "Jarman", "Jarrett", "Jarvis", "Jefferson", "Jeffreys", "Jenkins", "Jervis", "Jevon", "Jevons",
"Job", "John", "Johns", "Jones", "Joseph", "Kedwards", "Keffin", "Kendrick", "Kent", "Kenvin", "Kethin", "Kiffin", "Kinsey", "Lacharn", "Lagharn", "Lawrence",
"Lewis", "Leyshon", "Llewellen", "Lblewellin", "Llewellyn", "Llowarch", "Lloyd", "Lloyds", "Lodwick", "Lougher", "Loyd", "Loyn", "Lucas", "Mabe", "Maddock",
"Maddox", "Maddy", "Madock", "Madox", "Mady", "Mansel", "Manuel", "Martin", "Mason", "Mathews", "Mathias", "Matthew", "Matthews", "Maurice", "Mayberry",
"Maybery", "Mayn", "Means", "Mellens", "Melling", "Meredith", "Merrick", "Methuen", "Meyler", "Meyrick", "Michael", "Miles", "Mill", "Mills", "Milo", "Morgan",
"Morris", "Morse", "Morys", "Mostyn", "Moyle", "Nanney", "Narbett", "Nash", "Nevet", "Newell", "Nichol", "Nicholas", "Nicholls", "Noke", "Nuttall", "Oakley",
"Obray", "Onions", "Owain", "Owen", "Owens", "Paish", "Parker", "Parry", "Paskin", "Paul", "Pearce", "Pearse", "Pearson", "Peat", "Peate", "Pendry", "Pennant",
"Peregrine", "Perkin", "Perkins", "Perkyn", "Peters", "Phelps", "Phillips", "Philpin", "Picton", "Pierce", "Popkin", "Popkins", "Powell", "Powelson", "Powys",
"Preddy", "Predith", "Preece", "Price", "Prichard", "Prickett", "Pritchard", "Pritchett", "Probart", "Probert", "Probyn", "Propert", "Prosser", "Protheroe",
"Prydderch", "Prys", "Pryse", "Prytherch", "Pugh", "Pullin", "Pumphrey", "Pyrs", "Quilt", "Radclyffe", "Raglan", "Reece", "Rees", "Reynold", "Reynolds",
"Rhiann", "Rhydderch", "Rhys", "Rice", "Richards", "Rickard", "Rickett", "Roberts", "Robin", "Roderick", "Rogers", "Rosier", "Rosser", "Rothero", "Rowland",
"Rowlands", "Ruddock", "Ruther", "Rynallt", "Rynalt", "Saer", "Sais", "Salbri", "Salebiri", "Salmon", "Salusbury", "Sambrook", "Sambroth", "Samrook",
"Samuel", "Samwell", "Sandbrook", "Sayce", "Sayers", "Says", "Sayvage", "Seys", "Sheen", "Sheldon", "Simons", "Smith", "Smooth", "Stephens", "Stevens",
"Stradling", "Swancott", "Tanat", "Tannatt", "Tarvin", "Taylor", "Teague", "Tegan", "Tegg", "Tegue", "Tew", "Thomas", "Tibbett", "Tibbetts", "Tibbitt",
"Tibbot", "Timothy", "Tither", "Treffgarne", "Treharne", "Trevor", "Trewent", "Tucker", "Tudor", "Tugh", "Turner", "Upjohn", "Uprichard", "Vain", "Vallant",
"Vane", "Vaughan", "Wace", "Walters", "Wardlow", "Warlow", "Warren", "Waters", "Watkins", "Watkiss", "Watt", "Watts", "Weaver", "Welch", "Welling", "Wellins",
"Welsh", "Whittal", "Wild", "Wilding", "Williams", "Willis", "Wilson", "Withers", "Wogan", "Woosencroft", "Worthing", "Wyn", "Wynn", "Wynne", "Young"};

inline vector<string> TieflingMascFirstNames= {"Adebugi", "Adiatorix", "Adnamati", "Advorix", "Agedillios", "Agisilius", "Albic", "Allobroxus",
"Alpius", "Ambaxius", "Ambillus", "Ambiorix", "Andecamulos", "Andecarius", "Andegasi", "Andergi", "Andosteni", "Annmoris", "Artos", "Ateano",
"Atepagus", "Ateponius", "Atesios", "Atessatis", "Atporix", "Atrectus", "Atrixtos", "Aventinus", "Balorix", "Banui", "Bellognatus", "Bilicedo",
"Bimmos", "Bodocenos", "Borili", "Borso", "Borvonicus", "Bratronos", "Britomartus", "Brocchus", "Bussumarus", "Cabiros", "Cacurio", "Cambus", "Camerianus",
"Camulixus", "Caractacus", "Caracus", "Caramantius", "Carathounus", "Carigo", "Carix", "Carugenus", "Cassicius", "Cassivellaunus", "Catacus", "Cathirix",
"Caticorix", "Cattabus", "Cattuvir", "Catuenus", "Catumandus", "Catusius", "Catuvolcus", "Cauarius", "Celtillus", "Cenno", "Cimarus", "Cingetorix", "Cinto",
"Coaeddus", "Cobledulitavus", "Cobnertius", "Cocolitanus", "Cogidubnus", "Comnertus", "Congonetiacus", "Contesilo", "Contoutos", "Corbagni", "Corio", "Cornutos",
"Cotillus", "Cottius", "Cottro", "Covertomotul", "Covirius", "Criciro", "Cunigni", "Cunobelinos", "Curcagnus", "Dagillus", "Dagobius", "Dalagni", "Dattovir",
"Deoratus", "Dercillus", "Devus", "Diorix", "Divicatus", "Dobagni", "Doiros", "Doninus", "Donnadu", "Donnus", "Drutalus", "Dumnorix", "Dumnovellaunus", "Ebicatos",
"Eburio", "Elusconos", "Endovellicus", "Epatus", "Epetinus", "Eporedorix", "Epos", "Epotsorouidus", "Ercaviccas", "Escincos", "Excingillus", "Exsomnus", "Frontú",
"Gabrus", "Genetlus", "Grimiggni", "Iantinus", "Iccauos", "Iccinus", "Ientius", "Licnos", "Litavis", "Litugenius", "Lugotorix", "Lugurix", "Macareus", "Maccis",
"Magurius", "Mando", "Martalos", "Martoualos", "Meddugnatus", "Megaravico", "Melmandus", "Messillus", "Metilius", "Moddagni", "Morirex", "Netacari", "Nisigni",
"Oclicnos", "Ollognus", "Oppianicnos", "Orgetorix", "Perrius", "Praesutagus", "Reginius", "Remicus", "Rextugenos", "Rittuvvecas", "Sacrovir", "Sagillus", "Samais",
"Samocenus", "Segovax", "Senecio", "Senocarus", "Senovir", "Sollovico", "Talius", "Tallutius", "Tanco", "Tarbunus", "Tasciovanus", "Tascius", "Tasgetios", "Tauri",
"Togodumnus", "Toutio", "Toutobocio", "Toutos", "Trenacatus", "Tritos", "Tuticanius", "Ulccagni", "Vallius", "Vallo", "Vebru", "Vectimarus", "Vectitos", "Velagenus",
"Velitas", "Velorius", "Velugni", "Vendogni", "Venextos", "Venicarus", "Venixamus", "Vennonius", "Vepotalus", "Vercatus", "Vercassivellaunus", "Vercingetorix",
"Vercombogius", "Versignos", "Verter", "Vertros", "Veruico", "Vicixtillus", "Victi", "Vindedo", "Viranus", "Viratus", "Viriacius", "Virico", "Virisimi", "Virocantus",
 "Vitousurix", "Vlatcani", "Vlatos", "Vlatugni", "Vocorix", "Vopiscus", "Vosegus", "Voteporix"};

inline vector<string>  TieflingFemmeFirstNames = {"Abrexta", "Adginna", "Adiania", "Adiega", "Admata", "Adnamitu", "Adnamu", "Aduorix", "Advorix", "Aesica", "Agedia",
"Aia", "Albina", "Alla", "Alleticia", "Allusa", "Alpina", "Alteurita", "Andebrocirix", "Anderca", "Anderica", "Anderina", "Andoca", "Annama", "Arrotala",
"Atectorigiana", "Atessatia", "Atioxta", "Auctiona", "Audata", "Aulricmara", "Banna", "Banona", "Barita", "Betudaca", "Bileseton", "Billia", "Borissa", "Boudenna",
"Boudicca", "Boudilatis", "Brocchia", "Buscilla", "Cabrilla", "Cabura", "Caburena", "Caccosa", "Camula", "Cantexta", "Carantia", "Carantusa", "Carata", "Caretosa",
"Carissa", "Cartimandua", "Castina", "Catalia", "Catica", "Catronia", "Catta", "Cattulla", "Caturica", "Caura", "Cenna", "Cenos", "Centogenea", "Centusmia", "Cigemma",
"Cinia", "Coblanuo", "Cobnerta", "Cobronia", "Comatimara", "Condexua", "Congenetia", "Corasia", "Corobilla", "Cottina", "Cotu", "Cotuconi", "Cricconia", "Cunacena",
"Cunoarda", "Cunovinda", "Dania", "Dannumara", "Danu", "Deuilla", "Diligenta", "Diveca", "Donilla", "Dubna", "Eliomara", "Elovissa", "Epilla", "Eppaxta", "Eppia",
"Eskenga", "Exapia", "Excinga", "Excingilla", "Exobna", "Fimmilene", "Friagabi", "Genna", "Genucia", "Gnatia", "Huctia", "Iantulla", "Iatta", "Iccia", "Ilateuta",
"Inderca", "Isosae", "Lanipendia", "Leuca", "Leucona", "Lituccia", "Litugena", "Loucita", "Loucitta", "Maccira", "Magusatia", "Manduissa", "Martilia", "Martna",
"Mata", "Mataura", "Matina", "Matonia", "Mattosa", "Matugena", "Medlotama", "Melicia", "Messilia", "Metilia", "Moriena", "Mottu", "Nama", "Namia", "Namiola", "Namu",
"Namuta", "Nantia", "Nantiorix", "Nerta", "Netelia", "Nitiogenna", "Ollia", "Orbiana", "Origena", "Oxidubna", "Paulla", "Pera", "Peula", "Potita", "Reginia", "Rematia",
"Ressatu", "Ressona", "Reticiana", "Ritomara", "Sagila", "Sama", "Samaxa", "Samia", "Sammiola", "Sattomata", "Sedecennis", "Segolia", "Sennaucia", "Severa", "Sila",
"Suaduilla", "Sucaria", "Sueta", "Sumela", "Talavica", "Talisia", "Taluppa", "Talussa", "Tancorix", "Tascilla", "Taurica", "Teolugnia", "Teuta", "Tritia", "Trocina",
"Valagenta", "Valicina", "Vebrumna", "Veca", "Vectinia", "Vellibia", "Veniala", "Venicia", "Venisama", "Venitouta", "Venixama", "Venna", "Vennonia", "Verctissa",
"Verica", "Verodumna", "Vicana", "Viccu", "Viccus", "Victisirana", "Vindauscia", "Viralira", "Viratia", "Virciu", "Viriondaga", "Visurix", "Vlatucia", "Vocara",
"Vrittia", "Vrogenia"};

inline vector<string>  TieflingLastNames = {"Cadurci", "Carnutes", "Cimbri", "Mattiaci", "Nemetes", "Sequani", "Sugambri", "Teutoni", "Triboci", "Ubii",
"Vangiones", "Venelli", "Sedlak", "Szereban", "Taran", "Vanan", "Zatchet", "Markolak", "Raeburn", "Aimery", "Donoghan", "Leerstrom", "Carnago",
"Benak", "Falken", "Umbermoor", "Wendell"};

inline vector<string>  OrcMascFirstNames = {"Adomnán", "Áed", "Áedgen", "Áengus", "Affiath", "Ailchú", "Ailerán", "Ailill", "Aindíles", "Ainmere", "Airard", "Airbertach",
"Amalgaid", "Amargein", "Amlaíb", "Anfudán", "Anmchaid", "Artt", "Artúr", "Assíd", "Báetán", "Báethchellach", "Báethgalach", "Báethíne", "Baiscend", "Banbán", "Bécc",
"Beollán", "Blathmac", "Bran", "Bressal", "Brian", "Briccéne", "Bróccan", "Búadach", "Búadachán", "Caicher", "Cailte", "Cairpre", "Cáirthenn", "Carthach", "Cathal",
"Cathalán", "Cathassach", "Cellach", "Cenn Fáelad", "Cennétig", "Cerball", "Cernach", "Cernachán", "Cett", "Cian", "Cillíne", "Cináed", "Clérchéne", "Cobthach", "Colcu",
"Colmán", "Columb", "Conaing", "Conall", "Conchobar", "Condlae", "Congal", "Congalach", "Conlae", "Conmacc", "Conn", "Connla", "Cormac", "Cormacán", "Coscrach",
"Crimthann", "Crinán", "Crundmáel", "Cú Maige", "Cú Mara", "Cú Roí", "Cú Slébe", "Cú Ulad", "Cúán", "Cuilén", "Cuilénán", "Cuindles", "Cummascach", "Dabíd", "Dáire",
"Dálach", "Dauíd", "Demmán", "Diarmait", "Dícuill", "Díglach", "Dímmae", "Dínertach", "Domhnall", "Domnall", "Donn Slébe", "Donnchad", "Donndubán", "Donngal", "Duarcán",
"Dubthach", "Duinechaid", "Dúnadach", "Dunchad", "Dúngal", "Dúnlang", "Echmhílidh", "Echthigern", "Énnae", "Eochaid", "Eochu", "Éogan", "Eoghan", "Ercc", "Érennach",
"Fáelán", "Faílbe", "Fearghas", "Fechtnach", "Fedacch", "Fedelmid", "Feradach", "Ferchar", "Ferdomnach", "Fergal", "Fergus", "Fhearchar", "Fiachna", "Fiachra",
"Fiachrae", "Fiachu", "Finán", "Find", "Findchad", "Fíngin", "Finguine", "Finn", "Finnchú", "Fínnechta", "Fínsnechta", "Fintan", "Flaithbertach", "Flaithem",
"Flaithrí", "Fland", "Flann", "Flannacán", "Fogartach", "Forannán", "Forbassach", "Fothad", "Fothud", "Gabhran", "Gadra", "Gáethíne", "Garalt", "Gébennach",
"Gilla Brénainn", "Gilla Brigde", "Gilla Cáemgein", "Gilla Ciaráin", "Gilla Comgaill", "Gilla Críst", "Gilla Mochutu", "Gilla na Náem", "Gilla Pátraic",
"Glassán", "Gormán", "Gormgilla", "Guaire", "Ímar", "Imchad", "Indrechtach", "Labraid", "Lachtnán", "Lennán", "Liber", "Lóegaire", "Loingsech", "Lorccán", "Lugaid",
"Lughaidh", "Mac Bethad", "Mac Laisre", "Mac Raith", "Máel Brénainn", "Máel Brigde", "Máel Ciaráin", "Máel Coluim", "Máel Dúin", "Máel Fábaill", "Máel Finnén",
"Máel Ísu", "Máel Máedóc", "Máel Mithig", "Máel Mórda", "Máel Muad", "Máel Muire", "Máel Pátraic", "Máel Ruanaid", "Máel Sechnaill", "Máel Tuili", "Máelán",
"Máelodor", "Máenach", "Maine", "Marcán", "Mathgamain", "Móenach", "Morand", "Morrann", "Mugrón", "Muirchertach", "Muirecán", "Muiredach", "Muirgius", "Murchad",
"Nathí", "Nechtan", "Niall", "Nuadu", "Odar", "Óengus", "Óenucán", "Oisean", "Oisian", "Oisséne", "Ólchobar", "Orthanach", "Ragallach", "Rebachán", "Rechtabra",
"Rígbarddán", "Robertach", "Rónán", "Rúadacán", "Rúadán", "Ruaidrí", "Ruarcc", "Ruissíne", "Rumann", "Sáerbrethach", "Scandlán", "Scothíne", "Seán", "Sechnassach",
"Séigíne", "Selbach", "Senach", "Senchán", "Sétnae", "Sitric", "Suibne", "Tadc", "Tadhg", "Tairdelbach", "Tanaide", "Tigernach", "Tigernán", "Tighearnán",
"Tipraite", "Tomaltach", "Tomás", "Tressach", "Trian", "Tuathal", "Uaithne", "Uallgarg"};

inline vector<string> OrcFemmeFirstNames = {"Ablach", "Áedammair", "Affraic", "Aíbinn", "Aideen", "Aífe", "Ailbe", "Aileann", "Ailleann", "Áine", "Almaith", "Anga", "Anlaith",
"Aodhnait", "Aoibheann", "Aróc", "Barrdub", "Be Bhionn", "Bé Fáil", "Bébhinn", "Bél", "Belocc", "Ben Mide", "Ben Muman", "Bil", "Brigid", "Brigit", "Cacht",
"Caillech Domnaill", "Caillech Finnen", "Cainnech", "Caíntigern", "Caírech", "Catan", "Cellach", "Chrodoara", "Ciannait", "Ciar", "Cingit", "Clothra", "Cnes",
"Coblaith", "Cochrann", "Cocrich", "Cóemfhind", "Coímell", "Colan", "Columba", "Conandil", "Concessa", "Conchend", "Conchenn", "Condal", "Congan", "Crínóc", "Cróeb",
"Cuach", "Cumman", "Dailfind", "Dairine", "Damhnait", "Dar Cárthaind", "Dearbháil", "Dearbhorgaill", "Dechtire", "Deirdriu", "Der Bforgaill", "Der Draigen",
"Derbáil", "Dercco", "Derg", "Dianaim", "Doireand", "Doirend", "Dron", "Dubchoblaig", "Dubh", "Dubh Essa", "Dubh Lacha", "Dubh Lemna", "Dubhchobhlaigh", "Dubhgilla",
"Dúinsech", "Dúnlaith", "Eabha", "Eachraidh", "Eadain", "Echrad", "Éile", "Eilgri", "Eithne", "Elige", "Ellbríg", "Emer", "Érennach", "Ériu", "Etaín", "Ethne",
"Etromma", "Euginia", "Failend", "Faílenn", "Faimdid", "Fainche", "Fedelm", "Feidelm", "Fiathnait", "Fína", "Finbil", "Find", "Findchóem", "Findétand", "Findscuap",
"Fíne", "Finnecht", "Fionnabhair", "Flann", "Forbflaith", "Fuamnach", "Garb", "Gelgéis", "Gnathnad", "Gobnait", "Gormán", "Gormfhlaith", "Gormlaith", "Ibel", "Indécht",
"Inderb", "Indiu", "Íte", "Lann", "Lasair", "Lassar", "Lassi", "Lathir", "Lebarcham", "Lerben", "Lerthan", "Lethann", "Lí Ban", "Liadan", "Lígach", "Luiseach", "Macha",
"Máel Etich", "Máel Fabaill", "Máel Mide", "Máel Muire", "Martha", "Medb", "Meld", "Mincloth", "Móen", "Mongfhind", "Mór", "Mór Muman", "Muadhnait", "Mugain", "Muireann",
"Muirecht", "Muirenn", "Muirgel", "Muiriath", "Muirin", "Muirne", "Narbflaith", "Ném", "Némdaille", "Nessa", "Niamh", "Óchae", "Óebfhinn", "Orlaith", "Órnat", "Ragnailt",
"Ríoghnach", "Roach", "Rónnait", "Sadb", "Sadhbh", "Sáerlaith", "Samthann", "Saraid", "Sarnat", "Scathach", "Scáthdercc", "Sciath", "Sebdann", "Selblaith", "Sétach",
"Sín", "Sinech", "Sithmaith", "Sodelb", "Sogáes", "Suaibsech", "Táethen", "Tailefhlaith", "Taileflaith", "Tailltiu", "Téiti", "Temair", "Tlachtga", "Tómnat",
"Tuathflaith", "Uaithne", "Uallach", "Uasal", "Uathach"};

inline vector<string>  OrcLastNames = {"Alemanni", "Burgundii", "Chatti", "Bastarnae", "Batavi", "Chauci", "Cherusci", "Franconi", "Gepidae", "Gothi", "Ostrogothi",
"Visigothi", "Harudes", "Norici", "Suebi", "Hermundri", "Langobardi", "Marcomanni", "Quadi", "Tulingi", "Vandal"};
#endif /* Names_h */
